language: objective-c
matrix:
  fast_finish: true
env:
  - FORMULA=zeroc-ice34 BREW_OPTS=
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-python
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-java
before_script:
    - sudo easy_install pip
    - sudo pip install genshi --no-use-wheel
    - brew update
    - brew tap ome/alt
    - brew tap homebrew/science
    - brew audit Formula/*.rb
script:
    - VERBOSE=1 brew install Formula/$FORMULA.rb $BREW_OPTS
    - brew test Formula/$FORMULA.rb
