language: objective-c
matrix:
  fast_finish: true
env:
  - FORMULA=zeroc-ice34 BREW_OPTS=
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-python
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-java
  - FORMULA=omero BREW_OPTS=--only-dependencies
before_script:
    - brew update
    - brew tap ome/alt
    - brew tap homebrew/science
    - brew audit Formula/*.rb
script:
    - VERBOSE=1 brew install Formula/$FORMULA.rb $BREW_OPTS
    - brew test Formula/$FORMULA.rb
