language: objective-c
env:
  - FORMULA=bioformats BREW_OPTS=
  - FORMULA=bioformats BREW_OPTS=--devel
before_script:
    - brew update
    - brew audit Formula/*.rb
script: brew install Formula/$FORMULA.rb $BREW_OPTS
